name: Create Pull Request from main to prod on "prepare release"

on:
  push:
    branches:
      - main
    # Only trigger when commit message contains 'prepare release'
    # The regex checks for the keyword 'prepare release' in the commit message.
    commit-message: '.*prepare release.*'

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Create Pull Request from main to prod
        run: |
          # Fetch the latest changes from the remote
          git fetch origin

          # Create a pull request using GitHub CLI
          pr_title="Prepare release: Merge main into prod"
          pr_body="This pull request merges the latest changes from main to prod. Please review before merging."

          # Create pull request using GitHub CLI
          gh pr create --base prod --head main --title "$pr_title" --body "$pr_body" --label "auto-merge"

          echo "✅ Pull request created successfully!"